import {Track} from 'react-native-track-player';

export const playListData: Track[] = [
  {
    id: 1,
    title: 'United in Grief',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/United-In-Grief.mp3'),
  },
  {
    id: 2,
    title: 'N95',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/N95.mp3'),
  },
  {
    id: 3,
    title: 'Worldwide Steppers',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/Worldwide-Steppers.mp3'),
  },
  {
    id: 4,
    title: 'Die Hard',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/Die-Hard.mp3'),
  },
  {
    id: 5,
    title: 'Father Time',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/Father-Time.mp3'),
  },
  {
    id: 6,
    title: 'Rich Interlude',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/Rich-Interlude.mp3'),
  },
  {
    id: 7,
    title: 'Rich Spirit',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/Rich-Spirit.mp3'),
  },
  {
    id: 8,
    title: 'We Cry Together',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/We-Cry-Together.mp3'),
  },
  {
    id: 9,
    title: 'Purple Hearts',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale',
    duration: 1000,
    artwork: 'https://example.com/image.jpg',
    url: require('../assets/music/Purple-Hearts.mp3'),
  },
];
